# Travis CI build file for Kitura-redis.
# Kitura runs on OS X and Linux (Ubuntu v15.10).

# whitelist (branches that should be built)
branches:
  only:
    - master
    - develop
    - /^issue.*$/

notifications:
  slack:
    secure: "e6LnSUjiA/wZRVaJN9bdbzKrJxtl1D0sBosHs9BERIsek2VMgCN1Z4eFJk9ul/ePIEciaFWgOwJJO9ltC/tRburseDcgzSFNXO1hMasUvA+N3D8wxgnMTdzMnv+F7vbn613kuHFMRFoJFR1TWqahhlUGXvQFvGN+bx2InpZ8qcDmKGbWdk2LgIjF0lm9x+9hAlSKhcO9Dw93qQL8EGkmVJyhoYKL1usJbtpcFiJu6PQhmwM5JSH+5h0GISCoYsv+CKunqcBLfXeFyqT2LuZ1TcWXD3A0PCQQz3imOWhP4eZX9IyQS+E0ypOV8VqvUEyyl0v0Eirmjvh4smTQLlqWVITZe4BGri9+2V4rOocQK8HDbDeH1VuoXa36n9zJDDaMHoixank6n259YFhz5VgekVBMU3lGOvZ4+ax235cmOrF6WtRkY4oN+9AxoZ687A0164l3o+VoPJkpNdu2PZ8n2U2ATfYyqTUwluGPmVhS9YwkhMvDyEOu/EBxG0WcZjlAYQ4Ka2K2hiapulkqACYTeBU5cqMgkY4FOcwXzRqtEBSM0QPSxPFZoF2wNxPFc5DbNBXqRcaBjfyjgXjNhqrbVjHbE0iuM6vtAxXdRU6wrUIKx65cfa6vG/k8rfPG1kBpW2RQtC5s0tsTwBt+4ZUWNbWGzlSe01EkLr5CstzeG/A="

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
      env: SWIFT_VERSION=3.0.2
    - os: osx
      osx_image: xcode8.3
      sudo: required

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git
  - test -n "$SWIFT_VERSION" && echo "$SWIFT_VERSION" > .swift-version || echo "SWIFT_VERSION not set, using $(cat .swift-version)"

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
