# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'KituraCredentialsDemo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KituraCredentialsDemo

  pod 'Alamofire', '~> 4.0'
  pod 'Google/SignIn'

end
